-- =====================================================
-- BASE DE DATOS ORACLE - LIBRERÍA
-- =====================================================

-- =====================================================
-- TABLA: Author
-- =====================================================

CREATE TABLE Author (
    AuthorID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    AuthorName VARCHAR2(100) NOT NULL,

    CONSTRAINT pk_author
        PRIMARY KEY (AuthorID)
);

-- =====================================================
-- TABLA: Category
-- =====================================================

CREATE TABLE Category (
    CategoryID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CategoryDescription VARCHAR2(150) NOT NULL,

    CONSTRAINT pk_category
        PRIMARY KEY (CategoryID)
);

-- =====================================================
-- TABLA: Customer
-- =====================================================

CREATE TABLE Customer (
    CustomerID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    FirstName VARCHAR2(100) NOT NULL,
    LastName VARCHAR2(100) NOT NULL,
    ZipCode VARCHAR2(10),
    City VARCHAR2(100),
    State VARCHAR2(100),

    CONSTRAINT pk_customer
        PRIMARY KEY (CustomerID)
);

-- =====================================================
-- TABLA: Book
-- =====================================================

CREATE TABLE Book (
    BookID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CategoryID NUMBER,
    Title VARCHAR2(200) NOT NULL,
    ISBN VARCHAR2(20) UNIQUE,
    Year NUMBER(4),
    Price NUMBER(10,2),
    NoPages NUMBER,
    BookDescription CLOB,

    CONSTRAINT pk_book
        PRIMARY KEY (BookID),

    CONSTRAINT fk_book_category
        FOREIGN KEY (CategoryID)
        REFERENCES Category(CategoryID)
);

-- =====================================================
-- TABLA: Book_Order
-- =====================================================

CREATE TABLE Book_Order (
    OrderID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CustomerID NUMBER NOT NULL,
    OrderDate DATE NOT NULL,

    CONSTRAINT pk_book_order
        PRIMARY KEY (OrderID),

    CONSTRAINT fk_bookorder_customer
        FOREIGN KEY (CustomerID)
        REFERENCES Customer(CustomerID)
);

-- =====================================================
-- TABLA: Author_Book
-- =====================================================

CREATE TABLE Author_Book (
    AuthorID NUMBER NOT NULL,
    BookID NUMBER NOT NULL,

    CONSTRAINT pk_author_book
        PRIMARY KEY (AuthorID, BookID),

    CONSTRAINT fk_authorbook_author
        FOREIGN KEY (AuthorID)
        REFERENCES Author(AuthorID),

    CONSTRAINT fk_authorbook_book
        FOREIGN KEY (BookID)
        REFERENCES Book(BookID)
);

-- =====================================================
-- TABLA: Ordering
-- =====================================================

CREATE TABLE Ordering (
    BookID NUMBER NOT NULL,
    OrderID NUMBER NOT NULL,
    Price NUMBER(10,2) NOT NULL,

    CONSTRAINT pk_ordering
        PRIMARY KEY (BookID, OrderID),

    CONSTRAINT fk_ordering_book
        FOREIGN KEY (BookID)
        REFERENCES Book(BookID),

    CONSTRAINT fk_ordering_order
        FOREIGN KEY (OrderID)
        REFERENCES Book_Order(OrderID)
);