-- =====================================================
-- CREACIÓN DE BASE DE DATOS LÓGICA PARA ORACLE
-- SISTEMA DE TIENDA / VENTAS
-- =====================================================

-- NOTA:
-- En Oracle no se usa CREATE DATABASE normalmente
-- para proyectos escolares. Basta con crear las tablas
-- dentro del usuario/schema actual.

-- =====================================================
-- TABLA: Brands
-- =====================================================

CREATE TABLE Brands (
    BrandID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    BrandDescription VARCHAR2(255) NOT NULL,

    CONSTRAINT pk_brands
        PRIMARY KEY (BrandID)
);

-- =====================================================
-- TABLA: Products
-- =====================================================

CREATE TABLE Products (
    ProductID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    BrandID NUMBER,
    ProductName VARCHAR2(255) NOT NULL,

    CONSTRAINT pk_products
        PRIMARY KEY (ProductID),

    CONSTRAINT fk_products_brand
        FOREIGN KEY (BrandID)
        REFERENCES Brands(BrandID)
);

-- =====================================================
-- TABLA: Employees
-- =====================================================

CREATE TABLE Employees (
    EmployeeID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    FirstName VARCHAR2(100) NOT NULL,
    LastName VARCHAR2(100) NOT NULL,
    Title VARCHAR2(100),
    WorkPhone VARCHAR2(20),

    CONSTRAINT pk_employees
        PRIMARY KEY (EmployeeID)
);

-- =====================================================
-- TABLA: Shipping_Methods
-- =====================================================

CREATE TABLE Shipping_Methods (
    ShippingMethodID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ShippingMethod VARCHAR2(100) NOT NULL,

    CONSTRAINT pk_shipping_methods
        PRIMARY KEY (ShippingMethodID)
);

-- =====================================================
-- TABLA: Customers
-- =====================================================

CREATE TABLE Customers (
    CustomerID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CompanyName VARCHAR2(255),
    ContactName VARCHAR2(255),
    City VARCHAR2(100),
    State VARCHAR2(100),
    PostalCode VARCHAR2(20),
    PhoneNumber VARCHAR2(20),

    CONSTRAINT pk_customers
        PRIMARY KEY (CustomerID)
);

-- =====================================================
-- TABLA: Orders
-- =====================================================

CREATE TABLE Orders (
    OrderID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ShippingMethodID NUMBER,
    EmployeeID NUMBER,
    CustomerID NUMBER,
    OrderDate DATE,
    Quantity NUMBER,
    UnitPrice NUMBER(10,2),
    Discount NUMBER(5,2),

    CONSTRAINT pk_orders
        PRIMARY KEY (OrderID),

    CONSTRAINT fk_orders_shipping
        FOREIGN KEY (ShippingMethodID)
        REFERENCES Shipping_Methods(ShippingMethodID),

    CONSTRAINT fk_orders_employee
        FOREIGN KEY (EmployeeID)
        REFERENCES Employees(EmployeeID),

    CONSTRAINT fk_orders_customer
        FOREIGN KEY (CustomerID)
        REFERENCES Customers(CustomerID)
);

-- =====================================================
-- TABLA: Order_Details
-- =====================================================

CREATE TABLE Order_Details (
    OrderDetailID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    OrderID NUMBER NOT NULL,
    ProductID NUMBER NOT NULL,
    Quantity NUMBER,
    UnitPrice NUMBER(10,2),
    Discount NUMBER(5,2),

    CONSTRAINT pk_order_details
        PRIMARY KEY (OrderDetailID),

    CONSTRAINT fk_orderdetails_order
        FOREIGN KEY (OrderID)
        REFERENCES Orders(OrderID),

    CONSTRAINT fk_orderdetails_product
        FOREIGN KEY (ProductID)
        REFERENCES Products(ProductID)
);

-- =====================================================
-- TABLA: Payment_Method
-- =====================================================

CREATE TABLE Payment_Method (
    PaymentMethodID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    PaymentMethod VARCHAR2(50) NOT NULL,

    CONSTRAINT pk_payment_method
        PRIMARY KEY (PaymentMethodID)
);

-- =====================================================
-- TABLA: Payment
-- =====================================================

CREATE TABLE Payment (
    PaymentID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    PaymentMethodID NUMBER NOT NULL,
    OrderID NUMBER NOT NULL,
    PaymentAmount NUMBER(10,2),
    PaymentDate DATE,
    CreditCardNumber VARCHAR2(20),
    CreditCardEXPDate VARCHAR2(10),
    CardHoldersName VARCHAR2(255),

    CONSTRAINT pk_payment
        PRIMARY KEY (PaymentID),

    CONSTRAINT fk_payment_method
        FOREIGN KEY (PaymentMethodID)
        REFERENCES Payment_Method(PaymentMethodID),

    CONSTRAINT fk_payment_order
        FOREIGN KEY (OrderID)
        REFERENCES Orders(OrderID)
);